#!/usr/bin/env python
"""Run simple MMWM use cases from a trained checkpoint.

Supported modes:
  - predict: one-step latent prediction from synthetic vector/action input
  - rollout: repeated latent transitions
  - tool: build the tool ecosystem and run a short tool-routing loop

The script can load ModelConfig from a checkpoint saved by train_mmwm_minari.py,
or from a JSON config generated by the dashboard.
"""

from __future__ import annotations

import argparse
import json
from dataclasses import asdict, fields, is_dataclass
from pathlib import Path
from typing import Any, Dict

import torch

from MMWM.config import ModelConfig, build_model, build_tool_ecosystem
from MMWM.containers import LatentPacket, ObservationPacket, ToolContext


def _model_config_from_mapping(payload: Dict[str, Any]) -> ModelConfig:
    allowed = {field.name for field in fields(ModelConfig)}
    return ModelConfig(**{k: v for k, v in payload.items() if k in allowed})


def _dashboard_config_to_model_config(payload: Dict[str, Any]) -> ModelConfig:
    mmwm = payload.get("mmwm", {})
    latent_dim = int(mmwm.get("latent_dim") or 64)
    hidden_dim = int(mmwm.get("hidden_dim") or 128)
    primary_dim = latent_dim * 4
    vector_dim = int(mmwm.get("vector_dim") or 16)
    action_dim = int(mmwm.get("action_dim") or 8)
    transition = str(mmwm.get("transition") or "mlp")
    memory = str(mmwm.get("memory") or "gru")
    encoder = str(mmwm.get("encoder") or "simple_multimodal")
    return ModelConfig(
        encoder_name=encoder,
        encoder_kwargs={
            "text_vocab_size": 256,
            "text_embed_dim": min(128, hidden_dim),
            "vector_input_dim": vector_dim,
            "image_channels": 3,
            "audio_channels": int(mmwm.get("audio_channels") or 1),
            "hidden_dim": hidden_dim,
        },
        latent_projector_kwargs={"input_dim": hidden_dim, "latent_dim": latent_dim, "use_norm": True},
        memory_name=memory,
        memory_kwargs={"input_dim": latent_dim * 2, "hidden_dim": latent_dim},
        action_encoder_kwargs={"action_dim": action_dim, "action_embed_dim": latent_dim},
        conditioner_kwargs={
            "latent_dim": primary_dim,
            "action_dim": latent_dim,
            "memory_dim": latent_dim,
            "out_dim": primary_dim,
        },
        transition_core_name=transition,
        transition_core_kwargs={"input_dim": primary_dim, "hidden_dim": primary_dim},
        prediction_head_kwargs={"hidden_dim": primary_dim, "latent_dim": latent_dim},
        decoder_configs=[("vector_reconstruction", {"latent_dim": latent_dim, "output_dim": vector_dim})],
    )


def load_config(checkpoint: Path, config_json: Path | None) -> ModelConfig:
    ckpt = torch.load(checkpoint, map_location="cpu", weights_only=False)
    cfg_payload = ckpt.get("model_config") or ckpt.get("config")
    if isinstance(cfg_payload, ModelConfig):
        return cfg_payload
    if is_dataclass(cfg_payload):
        return _model_config_from_mapping(asdict(cfg_payload))
    if isinstance(cfg_payload, dict):
        return _model_config_from_mapping(cfg_payload)

    if config_json is not None and config_json.exists():
        payload = json.loads(config_json.read_text(encoding="utf-8"))
        if "encoder_name" in payload:
            return _model_config_from_mapping(payload)
        return _dashboard_config_to_model_config(payload)
    raise ValueError(
        "Checkpoint does not contain model_config. Pass --config-json generated by the dashboard "
        "or train with the updated train_mmwm_minari.py."
    )


def load_model(checkpoint: Path, config: ModelConfig, device: torch.device):
    model = build_model(config).to(device)
    ckpt = torch.load(checkpoint, map_location=device, weights_only=False)
    state = ckpt.get("model_state_dict") or ckpt.get("model") or ckpt
    model.load_state_dict(state)
    model.eval()
    return model


def dims_from_config(config: ModelConfig) -> tuple[int, int]:
    vector_dim = int(config.encoder_kwargs.get("vector_input_dim", 16))
    action_dim = int(config.action_encoder_kwargs.get("action_dim", 8))
    return vector_dim, action_dim


def run_predict(model, config: ModelConfig, device: torch.device) -> Dict[str, Any]:
    vector_dim, action_dim = dims_from_config(config)
    obs = ObservationPacket(modalities={"vector": torch.randn(1, vector_dim, device=device)})
    action = torch.randn(1, action_dim, device=device)
    with torch.no_grad():
        output = model(obs, action, obs_tp1=None)
        decoded = model.decode(output.predicted_next_latent)
    return {
        "mode": "predict",
        "predicted_z_sem_shape": list(output.predicted_next_latent.z_sem.shape),
        "decoder_outputs": {k: list(v.shape) for k, v in decoded.items()},
    }


def run_rollout(model, config: ModelConfig, device: torch.device, steps: int) -> Dict[str, Any]:
    vector_dim, action_dim = dims_from_config(config)
    obs = ObservationPacket(modalities={"vector": torch.randn(1, vector_dim, device=device)})
    action = torch.randn(1, action_dim, device=device)
    memory = model.memory.init_state(batch_size=1, device=device)
    norms = []
    with torch.no_grad():
        latent = model.encode(obs)
        for _ in range(steps):
            transition = model.transition(latent, action, memory)
            latent = transition.next_latent
            memory = transition.next_memory
            norms.append(float(latent.z_sem.norm(dim=-1).mean().item()))
    return {"mode": "rollout", "steps": steps, "z_sem_norms": norms}


def run_tool(model, config: ModelConfig, device: torch.device, steps: int) -> Dict[str, Any]:
    vector_dim, action_dim = dims_from_config(config)
    registry, engine, _buffer, _promoter = build_tool_ecosystem(model, device=device, keep_hot_tools=4)
    obs = ObservationPacket(modalities={"vector": torch.randn(1, vector_dim, device=device)})
    action = torch.randn(1, action_dim, device=device)
    memory = model.memory.init_state(batch_size=1, device=device)
    with torch.no_grad():
        latent = model.encode(obs)
        packet = LatentPacket(state=latent, trace=["encode"])
        context = ToolContext(memory_state=memory, observation=obs, action=action, raw_inputs={})
        final_packet, trace = engine.iterate(packet, context, max_steps=steps)
    return {
        "mode": "tool",
        "registered_tools": [descriptor.tool_id for kind in ("internal", "decoder", "memory") for descriptor in registry.list_by_kind(kind)],
        "trace": trace,
        "final_trace": final_packet.trace,
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--mode", choices=["predict", "rollout", "tool"], required=True)
    parser.add_argument("--checkpoint", required=True)
    parser.add_argument("--config-json", default=None)
    parser.add_argument("--steps", type=int, default=5)
    parser.add_argument("--output", default=None)
    parser.add_argument("--device", default=None)
    args = parser.parse_args()

    checkpoint = Path(args.checkpoint)
    config_json = Path(args.config_json) if args.config_json else None
    device = torch.device(args.device or ("cuda" if torch.cuda.is_available() else "cpu"))
    config = load_config(checkpoint, config_json)
    model = load_model(checkpoint, config, device)

    if args.mode == "predict":
        result = run_predict(model, config, device)
    elif args.mode == "rollout":
        result = run_rollout(model, config, device, args.steps)
    else:
        result = run_tool(model, config, device, args.steps)

    text = json.dumps(result, indent=2)
    print(text)
    if args.output:
        out = Path(args.output)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()

